# Home Page
[[pages]]
path = "streamlit_app.py"
name = "🏠 Dashboard Home"
icon = ":house:"

# All Group Projects in Ascending Order

[[pages]]
name = "Group 001"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-001/app1.py"
name = "Group 001"
icon = ":page_facing_up:"

[[pages]]
name = "Group 002"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-002/app2.py"
name = "Group 002"
icon = ":page_facing_up:"

[[pages]]
name = "Group 003"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-003/app3.py"
name = "Group 003"
icon = ":page_facing_up:"

[[pages]]
name = "Group 004"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-004/app4.py"
name = "Group 004"
icon = ":page_facing_up:"

[[pages]]
name = "Group 005"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-005/app5.py"
name = "Group 005"
icon = ":page_facing_up:"

[[pages]]
name = "Group 006"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-006/app6.py"
name = "Group 006"
icon = ":page_facing_up:"

[[pages]]
name = "Group 007"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-007/app7.py"
name = "Group 007"
icon = ":page_facing_up:"

[[pages]]
name = "Group 008"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-008/app8.py"
name = "Group 008"
icon = ":page_facing_up:"



[[pages]]
name = "Group 010"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-010/app10.py"
name = "Group 010"
icon = ":page_facing_up:"

[[pages]]
name = "Group 011"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-011/app11.py"
name = "Group 011"
icon = ":page_facing_up:"

[[pages]]
name = "Group 012"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-012/app12.py"
name = "Group 012"
icon = ":page_facing_up:"



[[pages]]
name = "Group 014"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-014/app14.py"
name = "Group 014"
icon = ":page_facing_up:"

[[pages]]
name = "Group 015"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-015/app15.py"
name = "Group 015"
icon = ":page_facing_up:"

[[pages]]
name = "Group 016"
icon = ":bookmark_tabs:"
is_section = true

[[pages]]
path = "ENG220-Group-016/app16.py"
name = "Group 016"
icon = ":page_facing_up:"

[[pages]]
name = "Group 017"
icon = ":bookmark_tabs:"
is_section = true

